import type { SchemaField } from '@/types/provider'

export const anthropicRequestSchema: SchemaField[] = [
  {
    name: 'model',
    type: 'string',
    required: true,
    description:
      'The model that will complete your prompt (e.g. claude-sonnet-4-20250514, claude-haiku-4-20250414).',
  },
  {
    name: 'max_tokens',
    type: 'integer',
    required: true,
    description:
      'The maximum number of tokens to generate before stopping. Models may stop before reaching this maximum. This parameter is required by the Anthropic API.',
    providerNote: 'Required for Anthropic (unlike OpenAI where it is optional)',
  },
  {
    name: 'messages',
    type: 'array',
    required: true,
    description:
      'Input messages. Each message must have a role and content. The first message must use the user role.',
    children: [
      {
        name: 'role',
        type: 'string',
        required: true,
        description:
          'The role of the message author. Must be "user" or "assistant". System messages are specified via the top-level system parameter instead.',
      },
      {
        name: 'content',
        type: 'string',
        required: true,
        description:
          'The content of the message. Can be a string or an array of content blocks for multi-modal input.',
      },
    ],
  },
  {
    name: 'system',
    type: 'string',
    required: false,
    description:
      'System prompt. A system prompt is a way to provide context and instructions to the model. Unlike OpenAI, the system message is a top-level parameter rather than a message in the messages array.',
    providerNote:
      'Top-level parameter (not inside messages array like OpenAI)',
  },
  {
    name: 'temperature',
    type: 'number',
    required: false,
    default: '1',
    description:
      'Amount of randomness injected into the response. Ranges from 0.0 to 1.0. Use temperature closer to 0.0 for analytical/multiple choice tasks, and closer to 1.0 for creative and generative tasks.',
  },
  {
    name: 'top_p',
    type: 'number',
    required: false,
    description:
      'Use nucleus sampling. In nucleus sampling, the model considers the smallest set of tokens whose cumulative probability exceeds top_p. Recommended to use temperature or top_p but not both.',
  },
  {
    name: 'top_k',
    type: 'integer',
    required: false,
    description:
      'Only sample from the top K options for each subsequent token. Used to remove "long tail" low probability responses. Recommended for advanced use cases only.',
    providerNote: 'Anthropic only',
  },
  {
    name: 'stream',
    type: 'boolean',
    required: false,
    default: 'false',
    description:
      'Whether to incrementally stream the response using server-sent events (SSE). When true, the response will be a stream of events.',
  },
  {
    name: 'stop_sequences',
    type: 'array',
    required: false,
    description:
      'Custom text sequences that will cause the model to stop generating. The returned text will not contain the stop sequence.',
  },
  {
    name: 'metadata',
    type: 'object',
    required: false,
    description:
      'An object describing metadata about the request.',
    children: [
      {
        name: 'user_id',
        type: 'string',
        required: false,
        description:
          'An external identifier for the user who is associated with the request. This should be a uuid, hash value, or other opaque identifier.',
      },
    ],
  },
]

export const anthropicResponseSchema: SchemaField[] = [
  {
    name: 'id',
    type: 'string',
    required: true,
    description:
      'Unique object identifier. The format and length of IDs may change over time.',
  },
  {
    name: 'type',
    type: 'string',
    required: true,
    description:
      'Object type. For the Messages API, this is always "message".',
  },
  {
    name: 'role',
    type: 'string',
    required: true,
    description: 'Conversational role of the generated message. This will always be "assistant".',
  },
  {
    name: 'content',
    type: 'array',
    required: true,
    description:
      'Array of content blocks generated by the model. Each block has a type and associated data.',
    children: [
      {
        name: 'type',
        type: 'string',
        required: true,
        description:
          'The type of content block. Currently "text" for text responses and "tool_use" for tool call responses.',
      },
      {
        name: 'text',
        type: 'string',
        required: true,
        description: 'The generated text content (present when type is "text").',
      },
    ],
  },
  {
    name: 'model',
    type: 'string',
    required: true,
    description: 'The model that handled the request.',
  },
  {
    name: 'stop_reason',
    type: 'string',
    required: true,
    description:
      'The reason the model stopped generating. "end_turn" if the model reached a natural stopping point, "max_tokens" if the requested max_tokens was reached, or "stop_sequence" if one of the provided stop sequences was generated.',
  },
  {
    name: 'stop_sequence',
    type: 'string | null',
    required: true,
    description:
      'Which custom stop sequence was generated, if any. Null if the stop reason was not "stop_sequence".',
  },
  {
    name: 'usage',
    type: 'object',
    required: true,
    description: 'Billing and rate-limit usage information.',
    children: [
      {
        name: 'input_tokens',
        type: 'integer',
        required: true,
        description: 'The number of input tokens which were used.',
      },
      {
        name: 'output_tokens',
        type: 'integer',
        required: true,
        description: 'The number of output tokens which were used.',
      },
    ],
  },
]
